package com.javacrud.javacrud.documents;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

@Document(collection = "cycle")
public class Cycle {
    @Id
    private String id; // Auto-generated by MongoDB

    private String mdn; // The phone number of a customer
    private LocalDate startDate; // The start date of a billing cycle
    private LocalDate endDate; // The end date of a billing cycle
    private String userId; // Foreign key to the id of the user collection

    // Getter for id (MongoDB will automatically generate it)
    public String getId() {
        return id;
    }

    // Setter for mdn
    public void setMdn(String mdn) {
        this.mdn = mdn;
    }

    // Getter for mdn
    public String getMdn() {
        return mdn;
    }

    // Setter for startDate
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    // Getter for startDate
    public LocalDate getStartDate() {
        return startDate;
    }

    // Setter for endDate
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    // Getter for endDate
    public LocalDate getEndDate() {
        return endDate;
    }

    // Setter for userId
    public void setUserId(String userId) {
        this.userId = userId;
    }

    // Getter for userId
    public String getUserId() {
        return userId;
    }
}
