package com.javacrud.javacrud.documents;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Sharded;
import org.springframework.format.annotation.DateTimeFormat;
import com.javacrud.javacrud.util.DateManilpulation;
import java.util.Date;

@Document(collection = "cycle")
@Sharded(shardKey = {"userId", "mdn"})
public class Cycle {
    @Id
    @Indexed(unique = true)
    private String id; // Auto-generated by MongoDB
    private String userId; // Foreign key to the id of the user collection
    private String mdn; // The phone number of a customer

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date startDate; // The start date of a billing cycle

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private Date endDate; // The end date of a billing cycle

    @Value("${daysInACycle:30}") // Default value is 30
    private String daysInACycle;


    public Cycle(String mdn, Date startDate, String userId) {
        this.startDate = startDate;
        this.mdn = mdn;
        this.startDate = startDate;
        // Set endDate to daysInACycle from the start date and subtract 1 millisecond to avoid overlap
        this.endDate = new Date(
                DateManilpulation.addDaysToDate(startDate, 30).getTime()
                        - 1);
        this.userId = userId;
    }

    // Getter for id (MongoDB will automatically generate it)
    public String getId() {
        return id;
    }

    public String setId(String id) {
        return this.id = id;
    }

    // Setter for mdn
    public void setMdn(String mdn) {
        this.mdn = mdn;
    }

    // Getter for mdn
    public String getMdn() {
        return mdn;
    }

    // Setter for startDate
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    // Getter for startDate
    public Date getStartDate() {
        return startDate;
    }

    // Setter for endDate
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    // Getter for endDate
    public Date getEndDate() {
        return endDate;
    }

    // Setter for userId
    public void setUserId(String userId) {
        this.userId = userId;
    }

    // Getter for userId
    public String getUserId() {
        return userId;
    }
}
